[package]
name = "koggie"
version = "0.0.1"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
listenfd = "0.3"
opus = { path = "opus-rs" }
cala = "0.1"
